cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls', namespace='cart')),
    path('orders/',include('orders.urls',namespace='order_create')),
    path('payment/',include('payment.urls', namespace='payment')),
    path('',include('shop.urls',namespace='shop')),
]

if settings.DEBUG:urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}My Baajaar{% endblock %}</title>
        <link rel = "stylesheet" href = "{% static 'css/base.css' %}">
         
    </head>
    <body>
        <div id="header">
            <a href = "/" class ="logo">My Baajaar</a>
        </div>
        <div id="subheader">
            <div class="cart">
                {% with total_items=cart|length %}
                {% if total_items > 0 %} 
                Your cart:
                <a href="{% url 'cart:cart_detail' %}">
                    {{ total_items }} item{{ total_items|pluralize }},
                    ₹{{ cart.get_total_price}}
                </a>
                {% else %}
                    Your cart is empty.
                {% endif %} 
                {% endwith %}
            </div>
        </div>
        <div id="content">
            {% block content %} 
            {% endblock content %} 
        </div>
    </body>
</html>